Remove 1.2.0 e2e test
In 1.25 kubernetes version cert-manager ca injector does not work due to
the following error:

```
E0208 17:20:00.381911       1 start.go:119] cert-manager/ca-injector "msg"="manager goroutine exited" "error"=null
I0208 17:20:01.529717       1 request.go:645] Throttling request took 1.048204385s, request: GET:https://10.96.0.1:443/apis/cert-manager.io/v1?timeout=32s
E0208 17:20:02.081686       1 start.go:151] cert-manager/ca-injector "msg"="Error registering certificate based controllers. Retrying after 5 seconds." "error"="no matches for kind \"MutatingWebhookConfiguration\" in version \"admissionregistration.k8s.io/v1beta1\""
Error: error registering secret controller: no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"
```